-- SQL Script to set up Guardian Pharmacy application on Supabase

-- 1. Create Medicines Table
CREATE TABLE IF NOT EXISTS medicines (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT,
  condition TEXT,
  price NUMERIC,
  description TEXT,
  inStock BOOLEAN DEFAULT true,
  image_base64 TEXT, -- To store base64 image strings uploaded by Admin
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- 2. Create Doctors Table
CREATE TABLE IF NOT EXISTS doctors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  specialty TEXT,
  experience TEXT,
  image_base64 TEXT, -- To store base64 image strings uploaded/edited by Admin
  about TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- 3. Create Lab Tests Table
CREATE TABLE IF NOT EXISTS lab_tests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT,
  condition TEXT,
  price NUMERIC,
  originalPrice NUMERIC,
  discount TEXT,
  testsIncluded INTEGER,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- 4. Create Appointments Table
CREATE TABLE IF NOT EXISTS appointments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patientName TEXT NOT NULL,
  doctorId BIGINT REFERENCES doctors(id),
  doctorName TEXT,
  date TEXT,
  time TEXT,
  phone TEXT,
  reason TEXT,
  status TEXT DEFAULT 'Pending',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- 5. Set up basic Row Level Security Policies (Allow fully public access for this MVP)
ALTER TABLE medicines ENABLE ROW LEVEL SECURITY;
ALTER TABLE doctors ENABLE ROW LEVEL SECURITY;
ALTER TABLE lab_tests ENABLE ROW LEVEL SECURITY;
ALTER TABLE appointments ENABLE ROW LEVEL SECURITY;

-- Allow read/write access for all users (anon) for this simple setup. In a real production app with auth, 
-- you'd secure these to only allow admins to write.
CREATE POLICY "Public full access medicines" ON medicines FOR ALL TO public USING (true) WITH CHECK (true);
CREATE POLICY "Public full access doctors" ON doctors FOR ALL TO public USING (true) WITH CHECK (true);
CREATE POLICY "Public full access lab_tests" ON lab_tests FOR ALL TO public USING (true) WITH CHECK (true);
CREATE POLICY "Public full access appointments" ON appointments FOR ALL TO public USING (true) WITH CHECK (true);

-- Insert Some Initial Lab Tests Dummy Data
INSERT INTO lab_tests (name, category, condition, price, originalPrice, discount, testsIncluded) VALUES
('Complete Blood Count (CBC)', 'Blood Studies', 'General', 15.00, 20.00, '25%', 30),
('HbA1c Test', 'Diabetes', 'Diabetes', 25.00, 35.00, '28%', 3);

-- Insert Some Initial Medicines Dummy Data
INSERT INTO medicines (name, category, condition, price, description, inStock) VALUES
('Paracetamol 500mg', 'Fever & Pain', 'Fever', 2.50, 'Effective pain relief and fever reducer.', true),
('Amoxicillin 250mg', 'Antibiotics', 'General', 15.00, 'Treats bacterial infections. Prescription required.', true),
('Cetirizine 10mg', 'Allergy', 'Allergy', 5.20, 'Relief from allergy symptoms like sneezing.', true);

-- Insert Some Initial Doctors Dummy Data
INSERT INTO doctors (name, specialty, experience, about) VALUES
('Dr. Muralidharan', 'Dentist (BDS)', 'Experienced', 'Dr. Muralidharan is a highly experienced dentist dedicated to providing comprehensive dental care for families.'),
('Dr. Swaminathan', 'MD DVL (SKIN DOCTOR)', 'Experienced', 'Specializing in dermatology, Dr. Swaminathan utilizes the latest diagnostic technologies for optimal skin health.'),
('Dr. Uma maheswaran', 'Ortho (MS ORTHO D ORTHO)', 'Experienced', 'Expert orthopedist passionate about providing excellent orthopedic care and joint health treatments.'),
('Dr. Pragadeesh', 'MD', 'Experienced', 'Dr. Pragadeesh is a dedicated general physician providing comprehensive healthcare and medical guidance.');
